### ISSUE TITLE
Broken nvim 0.10 packages

### ISSUE THREAD

**Issue by anubhavp28** [conda-forge/nvim-feedstock#17] opened 2024-08-07 21:31 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The `nvim 0.10.1` conda package looks at the wrong place to `liblpeg.so`

```
╰─ ldd $(which nvim) | grep lpeg
        /spare/local/anubhavpatel/.micromamba/envs/nvim/lib/liblpeg.so => not found
```

### Installed packages

```shell
List of packages in environment: "/spare/local/anubhavpatel/.micromamba/envs/nvim"

  Name                Version       Build        Channel
─────────────────────────────────────────────────────────────────────────────
  _libgcc_mutex       0.1           conda_forge  files/channels/conda-forge
  _openmp_mutex       4.5           2_gnu        files/channels/conda-forge
  gettext             0.22.5        h59595ed_2   files/channels/conda-forge
  gettext-tools       0.22.5        h59595ed_2   files/channels/conda-forge
  gtest               1.14.0        h434a139_2   files/channels/conda-forge
  libasprintf         0.22.5        h661eb56_2   files/channels/conda-forge
  libasprintf-devel   0.22.5        h661eb56_2   files/channels/conda-forge
  libgcc-ng           14.1.0        h77fa898_0   files/channels/conda-forge
  libgettextpo        0.22.5        h59595ed_2   files/channels/conda-forge
  libgettextpo-devel  0.22.5        h59595ed_2   files/channels/conda-forge
  libgomp             14.1.0        h77fa898_0   files/channels/conda-forge
  libmpack-lua        1.0.12        hd590300_0   files/channels/conda-forge
  libstdcxx-ng        14.1.0        hc0a3c3a_0   files/channels/conda-forge
  libtermkey          0.22          hd590300_1   files/channels/conda-forge
  libtree-sitter      0.22.6        h4ab18f5_0   files/channels/conda-forge
  libuv               1.48.0        hd590300_0   files/channels/conda-forge
  libvterm            0.3.3         hd590300_0   files/channels/conda-forge
  libzlib             1.3.1         h4ab18f5_1   files/channels/conda-forge
  lua-lpeg            1.1.0         hd590300_0   files/channels/conda-forge
  luajit-openresty    2.1_20240314  hd590300_0   files/channels/conda-forge
  luv                 1.44.2        hd590300_0   files/channels/conda-forge
  msgpack-c           6.0.0         hfc55251_1   files/channels/conda-forge
  nvim                0.10.1        h40c8461_0   files/channels/conda-forge
  unibilium           2.1.1         hd590300_1   files/channels/conda-forge
```

### Environment info

```shell
╰─ mm info

       libmamba version : 1.5.6
     micromamba version : 1.5.6
           curl version : libcurl/8.7.1 OpenSSL/3.3.0 zlib/1.2.13 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.5
       envs directories : /spare/local/anubhavpatel/.micromamba/envs
          package cache : /spare/local/anubhavpatel/.micromamba/pkgs
            environment : nvim (active)
           env location : /spare/local/anubhavpatel/.micromamba/envs/nvim
      user config files : /apps/infrafs1/anubhavpatel/.mambarc
 populated config files : /apps/infrafs1/anubhavpatel/tower-forge/mambarc.yaml
       virtual packages : __unix=0=0
                          __linux=6.2.0=0
                          __glibc=2.35=0
                          __archspec=1=x86_64-v3
               channels : https://conda.devtools.tower-research.com/files/channels/tower/linux-64
                          https://conda.devtools.tower-research.com/files/channels/tower/noarch
                          https://conda.devtools.tower-research.com/files/channels/tower-forge/linux-64
                          https://conda.devtools.tower-research.com/files/channels/tower-forge/noarch
                          https://conda.devtools.tower-research.com/files/channels/conda-forge/linux-64
                          https://conda.devtools.tower-research.com/files/channels/conda-forge/noarch
       base environment : /spare/local/anubhavpatel/.micromamba
               platform : linux-64
```

**Comment by anjos** [comment] 2024-08-08 18:25
I'm not using micromamba, but [pixi](https://pixi.sh) instead.  I cannot reproduce this issue - for me, version 0.10.1 links correctly to liblpeg.so under linux:

```sh
$ ldd </path/to>/neovim/.pixi/envs/default/bin/nvim | grep liblpeg
	</path/to>/neovim/.pixi/envs/default/lib/liblpeg.so (0x00007fc154780000)
```

**Comment by anjos** [comment] 2024-08-08 18:29
And the list of relevant packages:

```sh
$ pixi list --manifest-path pixi.toml -e default | rg 'nvim|lpeg'
lua-lpeg                              1.1.0         h4bc722e_1          44.6 KiB   conda  lua-lpeg-1.1.0-h4bc722e_1.conda
nvim                                  0.10.1        h40c8461_0          7.3 MiB    conda  nvim-0.10.1-h40c8461_0.conda
```

Strangely, my hashes are different than yours for lua-lpeg - may be you can try to re-install from scratch (instead of updating it)?

**Comment by anjos** [comment] 2024-10-03 16:00
I'm closing this issue after no feedback since nearly 2 months.  Please re-open if you think the issue is actually related to this feedstock.

**Closed by anjos** 2024-10-03 16:00 UTC
Labels: bug
